# Generated by Django 4.2.13 on 2024-07-07 11:32

import blogs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('arts', 'ARTS'), ('games', 'GAMES'), ('home', 'HOME'), ('health', 'HEALTH'), ('technology', 'TECHNOLOGY'), ('recreation', 'RECREATION'), ('business', 'BUSINESS'), ('society', 'SOCIETY'), ('sports', 'SPORTS'), ('science', 'SCIENCE')], max_length=100)),
                ('description', models.TextField()),
                ('preview_image', models.FileField(blank=True, null=True, upload_to=blogs.models.blog_upload_to)),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('publish', 'PUBLISH')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blog')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Applaud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applauds', to='blogs.blog')),
            ],
            options={
                'db_table': 'applaud',
            },
        ),
    ]
