# Generated by Django 4.2.13 on 2024-07-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_comment_user_id_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
